from typing import Protocol, Optional
import asyncio
from app.models import BroadcastEvent


class ChatState(Protocol):
    """Abstraction for state management — router depends on this, not the concrete AppState."""
    async def register_chat(self, chat_id: int) -> bool: ...
    async def unregister_chat(self, chat_id: int) -> bool: ...
    async def broadcast(self, event: BroadcastEvent) -> None: ...
    async def add_queue(self, q: asyncio.Queue) -> None: ...
    async def remove_queue(self, q: asyncio.Queue) -> None: ...
    @property
    def active_chat_id(self) -> int | None: ...


class MessageGateway(Protocol):
    """Abstraction for any outbound messaging client."""
    async def send_message(self, chat_id: int, text: str) -> bool: ...
